import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Auto-Scan Triggers',
  description: 'How Veilguard scans automatically in every IDE. Rules files, hooks, trigger moments.',
};

export default function DocsAutoscanPage() {
  return (
    <>
      <h1 className="text-4xl font-semibold mb-4">Auto-Scan Triggers</h1>
      <p className="text-xl text-text-body mb-10">
        You never run a scan manually. The AI triggers the right scanner exactly when context demands it.
      </p>

      <h2 className="text-2xl font-medium mt-10 mb-4 border-b border-border pb-2">Trigger Moments</h2>
      <ul className="space-y-4 not-prose mb-12">
        <li className="flex items-start gap-4 p-4 rounded-lg bg-background-code border border-border text-sm">
          <div className="w-1/3 font-medium text-text-heading">File Created/Modified</div>
          <div className="w-2/3 text-text-body">→ Triggers <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">scan_secrets</code> immediately before completion.</div>
        </li>
        <li className="flex items-start gap-4 p-4 rounded-lg bg-background-code border border-border text-sm">
          <div className="w-1/3 font-medium text-text-heading">API Route Changes</div>
          <div className="w-2/3 text-text-body">→ Triggers <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">scan_webhooks</code> and <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">scan_injection</code>.</div>
        </li>
        <li className="flex items-start gap-4 p-4 rounded-lg bg-background-code border border-border text-sm">
          <div className="w-1/3 font-medium text-text-heading">DB Schema Changes</div>
          <div className="w-2/3 text-text-body">→ Triggers <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">check_supabase_rls</code>.</div>
        </li>
        <li className="flex items-start gap-4 p-4 rounded-lg bg-background-code border border-border text-sm">
          <div className="w-1/3 font-medium text-text-heading">package.json Changes</div>
          <div className="w-2/3 text-text-body">→ Triggers <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">scan_dependencies</code> and <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">check_supply_chain</code>.</div>
        </li>
        <li className="flex items-start gap-4 p-4 rounded-lg bg-background-code border border-border text-sm">
          <div className="w-1/3 font-medium text-text-heading">Before Deploy</div>
          <div className="w-2/3 text-text-body">→ Triggers <code className="text-accent bg-accent-muted px-1.5 rounded mx-1">full_audit</code>.</div>
        </li>
      </ul>

      <h2 className="text-2xl font-medium mt-10 mb-4 border-b border-border pb-2">How it works per IDE</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 not-prose">
        <div className="p-6 bg-background-card border border-border rounded-xl">
          <h3 className="text-lg font-medium text-text-heading mb-2">Claude Code</h3>
          <p className="text-sm text-text-muted">Utilizes built-in pre-commit and prompt hooks automatically generated by Veilguard.</p>
        </div>
        <div className="p-6 bg-background-card border border-border rounded-xl">
          <h3 className="text-lg font-medium text-text-heading mb-2">Cursor</h3>
          <p className="text-sm text-text-muted">Managed entirely through constraints embedded in <code className="bg-background-code px-1 rounded">.cursorrules</code>.</p>
        </div>
        <div className="p-6 bg-background-card border border-border rounded-xl">
          <h3 className="text-lg font-medium text-text-heading mb-2">Windsurf</h3>
          <p className="text-sm text-text-muted">Managed through Cascade prompt rules injected automatically via <code className="bg-background-code px-1 rounded">.windsurfrules</code>.</p>
        </div>
        <div className="p-6 bg-background-card border border-border rounded-xl">
          <h3 className="text-lg font-medium text-text-heading mb-2">VS Code (Roo/Cline)</h3>
          <p className="text-sm text-text-muted">Driven by the base system prompt specifying rule triggers.</p>
        </div>
      </div>
    </>
  );
}
